Dev env
prezly/themes-intl-messages pull request #32
Opened 2022-04-26 22:12 UTC by aspirisen

2022-04-27 08:22 UTC, oleg-semyonov requested changes

2022-04-27 08:22 UTC, oleg-semyonov commented on .github/workflows/prettier.yml
> +name: Prettier
Same comment as in `analytics`: https://github.com/prezly/analytics/pull/2#discussion_r859515418

2022-04-29 07:32 UTC, oleg-semyonov commented on .github/workflows/prettier.yml
> +name: Prettier
@aspirisen please update the workflow to match [the one in theme-kit-nextjs](https://github.com/prezly/theme-kit-nextjs/blob/main/.github/workflows/lint.yml) (which uses `wearerequired/lint-action`)

2022-04-29 09:23 UTC, oleg-semyonov requested changes
Oops, I was a bit to quick to approve..
Please check the Lint workflow checks, it seems that eslint was not even installed on the project 🤔 
The question is if we actually need it here, since there is not much code. 
Maybe running just prettier would be fine, but we can also install `eslint` and `@prezly/eslint-config`. 
Sorry for the confusion :(

2022-04-29 09:51 UTC, aspirisen commented
@oleg-semyonov could you look again

2022-04-29 10:31 UTC, merged