Fix build script
prezly/themes-intl-messages pull request #36
Opened 2022-05-04 07:39 UTC by aspirisen

PNPM does not execute post/pre builds and therefore build script i not self-sufficient

2022-05-05 07:15 UTC, oleg-semyonov requested changes

2022-05-05 07:15 UTC, oleg-semyonov commented on package.json
> +        "build": "tsc --project . && npm run intl:compile && npm run copy-messages",
This is weird, the `prebuild` and `postbuild` scripts should still be ran under normal circumstances.
Does your PNPM setup in `prezly-dev` ignore lifecycle scripts?
If so, it makes sense to create a separate script for it, which would run `npm run prebuild && npm run build && npm run postbuild`, to keep everything unified.

2022-05-12 10:00 UTC, oleg-semyonov requested changes

2022-05-12 10:09 UTC, aspirisen commented on package.json
> +        "build:full": "npm run build && npm run intl:compile && npm run copy-messages",
prebuild also runs `npm run prettier:check` what i think is not needed

2022-05-13 07:30 UTC, oleg-semyonov approved these changes

2022-05-13 08:06 UTC, merged